import type { Fact_Type } from 'src/types';

export const FACTS_LIST: Fact_Type[] = [
  {
    id: 'fact_1',
    title: 'Dawn feels magical for a reason',
    description: 'Fish often move shallow in low light.',
    tip: 'Start near the bank before going deeper.',
    isOpened: false,
  },
  {
    id: 'fact_2',
    title: 'Wind isn’t the enemy',
    description: 'It pushes food and baitfish into lanes.',
    tip: 'Fish the windward side first.',
    isOpened: false,
  },
  {
    id: 'fact_3',
    title: 'Shade is a hiding place',
    description: 'Overhangs, docks, and bridge shadows offer cover.',
    tip: 'Cast along the shadow edge, not the middle.',
    isOpened: false,
  },
  {
    id: 'fact_4',
    title: 'Current seams are highways',
    description: 'Fish hold where fast water meets slow water.',
    tip: 'Let your lure drift on the seam.',
    isOpened: false,
  },
  {
    id: 'fact_5',
    title: 'Points are underwater crossroads',
    description: 'Peninsulas and corners funnel movement.',
    tip: 'Fan-cast from shallow to deep.',
    isOpened: false,
  },
  {
    id: 'fact_6',
    title: 'Clear water needs stealth',
    description: 'Fish see you and your line more easily.',
    tip: 'Use lighter line and longer casts.',
    isOpened: false,
  },
  {
    id: 'fact_7',
    title: 'Muddy water needs presence',
    description: 'Visibility is low, so fish track vibration.',
    tip: 'Choose lures with thump or rattle.',
    isOpened: false,
  },
  {
    id: 'fact_8',
    title: 'Small ripples can be perfect',
    description: 'Too much calm can make fish cautious.',
    tip: 'Fish when the surface has a light texture.',
    isOpened: false,
  },
  {
    id: 'fact_9',
    title: 'Slow retrieves catch more than you think',
    description: 'When water is cool, fish conserve energy.',
    tip: 'Pause often and move less.',
    isOpened: false,
  },
  {
    id: 'fact_10',
    title: 'The drop-off edge is a dinner table',
    description: 'Depth changes concentrate feeding.',
    tip: 'Work parallel to the drop-off.',
    isOpened: false,
  },
  {
    id: 'fact_11',
    title: 'Weed lines are structure',
    description: 'They offer shade, oxygen, and ambush points.',
    tip: 'Cast along the weed edge, not into thick weeds.',
    isOpened: false,
  },
  {
    id: 'fact_12',
    title: 'Birds are free scouting',
    description: 'Diving and circling often means bait is nearby.',
    tip: 'Move toward activity quietly.',
    isOpened: false,
  },
  {
    id: 'fact_13',
    title: 'After light rain, fish may wake up',
    description: 'Oxygen increases and insects get knocked in.',
    tip: 'Fish shallow for a short window.',
    isOpened: false,
  },
  {
    id: 'fact_14',
    title: 'Sunny days: think deeper or darker',
    description: 'Bright light pushes fish to shade and depth.',
    tip: 'Target shadows or deeper water.',
    isOpened: false,
  },
  {
    id: 'fact_15',
    title: 'Cloudy days: fish roam more',
    description: 'Less light means more confidence to move.',
    tip: 'Cover more shoreline and keep casting.',
    isOpened: false,
  },
  {
    id: 'fact_16',
    title: 'Eddies are resting spots',
    description: 'Behind rocks and pillars, water slows down.',
    tip: 'Drop your lure into the calm swirl.',
    isOpened: false,
  },
  {
    id: 'fact_17',
    title: 'Watch for tiny V wakes',
    description: 'It can mean fish cruising near the surface.',
    tip: 'Cast ahead of the movement, not on it.',
    isOpened: false,
  },
  {
    id: 'fact_18',
    title: 'Noise travels far in water',
    description: 'Heavy steps and splashes can spook fish.',
    tip: 'Set gear down gently and move slower.',
    isOpened: false,
  },
  {
    id: 'fact_19',
    title: 'Tides redraw the map',
    description: 'Channels and troughs shift bite zones.',
    tip: 'Fish outgoing water where it funnels.',
    isOpened: false,
  },
  {
    id: 'fact_20',
    title: 'Your best tool is patience',
    description: 'The view is part of the catch.',
    tip: 'Give each spot 10 focused casts before moving.',
    isOpened: false,
  },
];
